FROM node:16.14.2-alpine3.15

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
#copies package.json and package-lock.json to Docker environment
COPY package.json package-lock.json ./
# Installs all node packages
RUN npm install 

# Copies everything over to Docker environment
COPY . .

RUN npm run build

RUN npm install -g http-server 

EXPOSE 3000

CMD [ "http-server", "build" ]
